import { MigrationInterface, QueryRunner } from "typeorm";

export class AddPocPhoneNumberToEvent1763380616546 implements MigrationInterface {
    name = 'AddPocPhoneNumberToEvent1763380616546'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payment_register"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "fk_assignments_register"`);
        await queryRunner.query(`ALTER TABLE "register" DROP CONSTRAINT "FK_register_payment"`);
        await queryRunner.query(`ALTER TABLE "register" DROP CONSTRAINT "fk_register_tenant"`);
        await queryRunner.query(`ALTER TABLE "register" DROP CONSTRAINT "register_location_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_assignments_rating"`);
        await queryRunner.query(`DROP INDEX "public"."idx_assignments_register_id"`);
        await queryRunner.query(`DROP INDEX "public"."register_email_key"`);
        await queryRunner.query(`DROP INDEX "public"."register_payment_id_key"`);
        await queryRunner.query(`DROP INDEX "public"."idx_register_role"`);
        await queryRunner.query(`DROP INDEX "public"."telegram_links_chat_id_key"`);
        await queryRunner.query(`DROP INDEX "public"."idx_telegram_links_chat_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_telegram_links_phone_number"`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "payment_screenshot_path"`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "is_admin"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "register" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "register" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "register" ADD "telegram_chat_id" character varying`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "UQ_54dcb35697d6d5825ab61c09d94" UNIQUE ("register_id")`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "file_name"`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "file_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "file_type"`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "file_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assignments" ALTER COLUMN "submission_date" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assignments" ALTER COLUMN "submission_date" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assignments" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assignments" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "context"`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "context" character varying`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "first_name" character varying`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "last_name" character varying`);
        await queryRunner.query(`ALTER TABLE "register" ADD CONSTRAINT "UQ_a25c9faec6801989b434563ed1b" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "state"`);
        await queryRunner.query(`ALTER TABLE "register" ADD "state" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "district"`);
        await queryRunner.query(`ALTER TABLE "register" ADD "district" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "mandal"`);
        await queryRunner.query(`ALTER TABLE "register" ADD "mandal" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "utr_number"`);
        await queryRunner.query(`ALTER TABLE "register" ADD "utr_number" character varying`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "register" ADD "password_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "tenant_id"`);
        await queryRunner.query(`ALTER TABLE "register" ADD "tenant_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "register" ADD "role" character varying NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "register" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "register" ADD CONSTRAINT "UQ_8a8a4760c30f2be5f2c6abf3a63" UNIQUE ("payment_id")`);
        await queryRunner.query(`ALTER TABLE "telegram_links" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "telegram_links" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "telegram_links" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "telegram_links" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_ca035feeb2659506a583f2d2fb" ON "telegram_links" ("phone_number") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_15c55465df44f5720fe056b0cb" ON "telegram_links" ("chat_id") `);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_54dcb35697d6d5825ab61c09d94" FOREIGN KEY ("register_id") REFERENCES "register"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_9d9a8e046de05a9e7ad9f379f56" FOREIGN KEY ("register_id") REFERENCES "register"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "register" ADD CONSTRAINT "FK_7f60e49c784a660bd52803f3c67" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "register" ADD CONSTRAINT "FK_8a8a4760c30f2be5f2c6abf3a63" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "register" DROP CONSTRAINT "FK_8a8a4760c30f2be5f2c6abf3a63"`);
        await queryRunner.query(`ALTER TABLE "register" DROP CONSTRAINT "FK_7f60e49c784a660bd52803f3c67"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_9d9a8e046de05a9e7ad9f379f56"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_54dcb35697d6d5825ab61c09d94"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15c55465df44f5720fe056b0cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca035feeb2659506a583f2d2fb"`);
        await queryRunner.query(`ALTER TABLE "telegram_links" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "telegram_links" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "telegram_links" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "telegram_links" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "register" DROP CONSTRAINT "UQ_8a8a4760c30f2be5f2c6abf3a63"`);
        await queryRunner.query(`ALTER TABLE "register" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "register" ADD "role" character varying(20) NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "tenant_id"`);
        await queryRunner.query(`ALTER TABLE "register" ADD "tenant_id" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "register" ADD "password_hash" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "utr_number"`);
        await queryRunner.query(`ALTER TABLE "register" ADD "utr_number" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "mandal"`);
        await queryRunner.query(`ALTER TABLE "register" ADD "mandal" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "district"`);
        await queryRunner.query(`ALTER TABLE "register" ADD "district" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "state"`);
        await queryRunner.query(`ALTER TABLE "register" ADD "state" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "register" DROP CONSTRAINT "UQ_a25c9faec6801989b434563ed1b"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "last_name" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "first_name" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "context"`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "context" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "assignments" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "assignments" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assignments" ALTER COLUMN "submission_date" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "assignments" ALTER COLUMN "submission_date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "file_type"`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "file_type" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "file_name"`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "file_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "UQ_54dcb35697d6d5825ab61c09d94"`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "telegram_chat_id"`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "register" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "register" ADD "is_admin" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "register" ADD "payment_screenshot_path" text`);
        await queryRunner.query(`ALTER TABLE "register" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`CREATE INDEX "idx_telegram_links_phone_number" ON "telegram_links" ("phone_number") `);
        await queryRunner.query(`CREATE INDEX "idx_telegram_links_chat_id" ON "telegram_links" ("chat_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "telegram_links_chat_id_key" ON "telegram_links" ("chat_id") `);
        await queryRunner.query(`CREATE INDEX "idx_register_role" ON "register" ("role") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "register_payment_id_key" ON "register" ("payment_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "register_email_key" ON "register" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_assignments_register_id" ON "assignments" ("register_id") `);
        await queryRunner.query(`CREATE INDEX "idx_assignments_rating" ON "assignments" ("rating") `);
        await queryRunner.query(`ALTER TABLE "register" ADD CONSTRAINT "register_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "register" ADD CONSTRAINT "fk_register_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenant_master"("tenant_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "register" ADD CONSTRAINT "FK_register_payment" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "fk_assignments_register" FOREIGN KEY ("register_id") REFERENCES "register"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payment_register" FOREIGN KEY ("register_id") REFERENCES "register"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
